---
websockify_version: 0.12.0

ood_extra_repos:
  - name: turbovnc
    file: turbovnc
    description: "TurboVNC official RPMs"
    baseurl: "https://packagecloud.io/dcommander/turbovnc/rpm_any/rpm_any/$basearch"
    gpgcheck: true
    async: true
    gpgkey: 
      - "https://packagecloud.io/dcommander/turbovnc/gpgkey"
      - "https://raw.githubusercontent.com/TurboVNC/repo/main/VGL-GPG-KEY"
      - "https://raw.githubusercontent.com/TurboVNC/repo/main/VGL-GPG-KEY-1024"
  - name: turbovnc-source
    file: turbovnc-source
    description: "TurboVNC official SRPMs"
    baseurl: "https://packagecloud.io/dcommander/turbovnc/rpm_any/rpm_any/SRPMS"
    gpgcheck: true
    async: true
    gpgkey:
      - "https://packagecloud.io/dcommander/turbovnc/gpgkey"
      - "https://raw.githubusercontent.com/TurboVNC/repo/main/VGL-GPG-KEY"
      - "https://raw.githubusercontent.com/TurboVNC/repo/main/VGL-GPG-KEY-1024"

turbovnc_packages:
  - turbovnc
  - pixman
  - xterm

additonal_packages:
  - python3-pip
  - xorg-x11-xauth

python_packages:
  - ts

group_packages:
  - xfce

turbovnc_bin_dir: "/opt/TurboVNC/bin"