---
- name: Ensure Kubectl is installed
  stat:
    path: "{{ bin_dir }}/kubectl"
  register: kubectl_binary

- name: Download kubectl to specified location {{ bin_dir }}
  get_url:
    url: "{{ kubectl_url }}"
    dest: "{{ bin_dir }}/kubectl"
    mode: 0755
    force: true
  become: true    
  when:
    - not kubectl_binary.stat.exists
    
- name: Copy k8s util files
  copy: 
    src: "{{ item.src }}" 
    dest: "{{ item.dest }}"
    mode: 0755
  loop:
    - src: files/
      dest: /bin/