---
- name: Download websockify archive
  ansible.builtin.get_url:
    url: https://github.com/novnc/websockify/archive/refs/tags/v{{ websockify_version }}.zip
    dest: /opt/websockify-{{ websockify_version }}.zip

- name: Extract websockify archive
  ansible.builtin.unarchive:
    src: /opt/websockify-{{ websockify_version }}.zip
    dest: /opt
    creates: /opt/websockify-{{ websockify_version }}
    remote_src: yes

- name: Rename websockify-{{ websockify_version }} to websockify
  shell: >-
    mv /opt/websockify-{{ websockify_version }} /opt/websockify

- name: List websockify dir
  command: ls -l /opt/websockify

- name: Python version
  command: python3 --version

- name: pip freeze
  command:  python3 -m pip freeze

- name: Run setup.py
  shell: >-
    python3 -m pip install .
  run_once: true
  args:
    chdir: "/opt/websockify"

- name: Clean up
  ansible.builtin.file:
    path: /opt/websockify-{{ websockify_version }}.zip
    state: absent
