---
- name: A demo to run ansible in a docker container
  hosts: all
  become: true
  roles:
    - { role: nesi.compute }
    - { role: nesi.ood-image }
    - { role: nesi.lmod }
    - { role: kubectl }