---
- name: NeSI Docker image playbook
  hosts: all
  become: true
  roles:
    - { role: nesi.compute }
    - { role: nesi.ood-image }
    - { role: nesi.lmod }
    - { role: nesi.turbovnc }
    - { role: nesi.websockify }
    - { role: kubectl }