- name: Ensure extra repos
  ansible.builtin.yum_repository: "{{ item }}" # noqa: args[module]
  loop: "{{ nesi_extra_repos }}"
  loop_control:
    label: "{{ item.name }}"

- name: Ensure the crb repository is enabled
  shell: dnf config-manager --set-enabled crb

- name: Install System Packages
  dnf:
    name: "{{ system_packages }}"
    state: present
    update_cache: true

- name: Get package_facts for checking if curl-minimal is installed
  ansible.builtin.package_facts:
    manager: auto

#- name: Print package facts
#  ansible.builtin.debug:
#    var: ansible_facts.packages

- name: Swap curl-minimal with curl (causes problems later)
  command: dnf -y swap curl-minimal curl
  when: "'curl-minimal' in ansible_facts.packages"

- name: Swap libcurl-minimal with libcurl (causes problems later)
  command: dnf -y swap libcurl-minimal libcurl
  when: "'libcurl-minimal' in ansible_facts.packages"

- name: Install Compute Packages
  dnf:
    name: "{{ compute_packages }}"
    state: present
    update_cache: true
