- name: Ensure extra repos
  ansible.builtin.yum_repository: "{{ item }}" # noqa: args[module]
  loop: "{{ nesi_extra_repos }}"
  loop_control:
    label: "{{ item.name }}"

- name: Ensure the crb repository is enabled
  shell: dnf config-manager --set-enabled crb

- name: Install System Packages
  dnf:
    name: "{{ system_packages }}"
    state: present
    update_cache: true

- name: Switch curl-minimal to curl
  command: dnf -y swap curl-minimal curl

- name: Install Compute Packages
  dnf:
    name: "{{ compute_packages }}"
    state: present
    update_cache: true
