---
- name: Ensure extra repos
  ansible.builtin.yum_repository: "{{ item }}" # noqa: args[module]
  loop: "{{ ood_extra_repos }}"
  loop_control:
    label: "{{ item.name }}"
    
- name: Install Compute Packages
  dnf:
    name: "{{ compute_packages }}"
    state: present

- name: "Add {{ turbovnc_bin_dir }} to PATH"
  lineinfile:
    path: /etc/environment
    line: 'PATH="{{ ansible_env.PATH }}:{{ turbovnc_bin_dir }}"'