---
name: Create and publish Docker images using Packer

on:
  push:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
#      - name: Install packer docker plugin
#        run: packer plugins install github.com/hashicorp/docker
#      - name: Install packer ansible plugin
#        run: packer plugins install github.com/hashicorp/ansible
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
#      - name: Build and push base image
#        run: |
#          export DOCKER_REPOSITORY="${REGISTRY}/${IMAGE_NAME}"
#          packer build base-template.json
#        working-directory: packer
#        env:
#          DOCKER_TAG: ${{ github.ref_name }}
      - name: Initialise packer for vnc image
        run:
          packer init -upgrade vnc-template.pkr.hcl
        working-directory: packer
      - name: Build and push vnc image
        run: |
          export PKR_VAR_docker_repository="${REGISTRY}/chrisdjscott/nesi-ondemand-vnc"
          packer build vnc-template.pkr.hcl
        working-directory: packer
        env:
          PKR_VAR_docker_tag: ${{ github.ref_name }}
      - name: push image
        run: docker image push "${REGISTRY}/chrisdjscott/nesi-ondemand-vnc:${PKR_VAR_docker_tag}"
        env:
          PKR_VAR_docker_tag: ${{ github.ref_name }}
